// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Caml_obj = require("bs-platform/lib/js/caml_obj.js");

function concat(comparators) {
  return (function (param, param$1) {
      var _comparators = comparators;
      var firstValue = param;
      var secondValue = param$1;
      while(true) {
        var comparators$1 = _comparators;
        if (comparators$1) {
          var result = Curry._2(comparators$1[0], firstValue, secondValue);
          if (result === 0) {
            _comparators = comparators$1[1];
            continue ;
          } else {
            return result;
          }
        } else {
          return Caml_obj.caml_compare(firstValue, secondValue);
        }
      };
    });
}

function by(comparator, firstValue, secondValue) {
  return Caml_obj.caml_compare(Curry._1(comparator, firstValue), Curry._1(comparator, secondValue));
}

exports.concat = concat;
exports.by = by;
/* No side effect */
